### ISSUE TITLE
JSON Parsing Error

### ISSUE THREAD

**Issue by corykim0829** [DevJuicy/EcoPlayer#2]
<img src="https://user-images.githubusercontent.com/34022757/79095870-8cdbc180-7d96-11ea-8591-99a1c0ed3d0b.png" width="600px">

**Comment by JuicyPark** [comment]
예외 URL을 넣어주는 경우에 에러가 생기는군요
[예외URL]
1. 유튜브에서 삭제된 동영상 URL
2. 플레이리스트 형식의 URL

일단 둘다 리스트에서 빼놓은 상태라 이제 플레이해보면 되긴 합니다. 예외처리를 어떻게 해야할지 막막하네요

-----------

[예외1번 예시]
![image](https://user-images.githubusercontent.com/31693348/79104794-44c69a00-7daa-11ea-97b9-3f8d8e67eeb7.png)

[예외2번 예시]
![image](https://user-images.githubusercontent.com/31693348/79104776-37111480-7daa-11ea-9301-6687e0637ede.png)
